# Generated by Django 3.1 on 2021-03-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210301_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_last_modified',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', help_text='User Image', null=True, upload_to='user_profile_pics'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_you_followed', models.DateField(auto_now_add=True)),
                ('follow_idol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_idol', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
