# Generated by Django 3.1 on 2021-03-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210301_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.png', help_text='User Image', null=True, upload_to='user_profile_pics'),
        ),
    ]
