# Generated by Django 3.1 on 2021-03-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow_idol',
            new_name='following',
        ),
    ]
