# Generated by Django 3.1 on 2021-03-02 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('react_chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scream',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
