# Generated by Django 3.1 on 2021-03-02 19:39

from django.db import migrations, models
import react_chat_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('react_chat_app', '0002_auto_20210302_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_posted']},
        ),
        migrations.AlterModelOptions(
            name='scream',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='scream',
            name='scream_code',
            field=models.CharField(default=react_chat_app.models.unique_key, max_length=50),
        ),
    ]
