# Generated by Django 3.1 on 2021-03-05 04:15

from django.db import migrations, models
import react_chat_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('react_chat_app', '0003_auto_20210302_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scream',
            name='scream_code',
            field=models.CharField(default=react_chat_app.models.unique_key, max_length=50, null=True),
        ),
    ]
