# Generated by Django 3.1 on 2021-03-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('react_chat_app', '0004_auto_20210305_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scream',
            options={},
        ),
    ]
