# Generated by Django 3.1 on 2021-03-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_chat_app', '0005_auto_20210308_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=500, upload_to='posts/images/%Y%M%D', width_field=100)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=100, null=True)),
                ('video', models.FileField(upload_to='posts/images/%Y%M%D')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['date_posted'],
            },
        ),
    ]
