# Generated by Django 3.1 on 2021-03-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('react_chat_app', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_connected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='react_chat_app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=500, null=True, upload_to='posts/images/%Y%M%D', width_field=100),
        ),
    ]
