# Generated by Django 3.1 on 2021-03-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_chat_app', '0008_post_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=500, null=True, upload_to='posts/images/%Y%M%D', width_field=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='posts/images/%Y%M%D'),
        ),
    ]
