# Generated by Django 3.1 on 2021-03-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_chat_app', '0009_auto_20210312_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.FileField(blank=True, upload_to='posts/%Y%M%D'),
        ),
    ]
